version: '3.8'

services:
  app:
    image: vulnerable-web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    restart: always
